print("Pulkit mantri\n24BEE117")

name = input("Enter the name")
rollnumber = input("Enter the rollnumber")
Email =input("Enter the email")
mobilenumber=input("Enter the mobile number")
print(f"Name: {name}")
print(f"Roll Number: {rollnum}")
print(f"Email: {Email}")
print(f"Mobile number: {mobilenum}")
